export default function PrivacyPolicy() {
  return (
    <div
      style={{
        maxWidth: 720,
        margin: "0 auto",
        padding: "3rem 1.5rem",
        fontFamily: "Georgia, serif",
        color: "#111",
        background: "#fff",
        lineHeight: 1.7,
      }}
    >
      <h1 style={{ fontSize: "2rem", marginBottom: "0.25rem" }}>
        Privacy Policy - Zera
      </h1>
      <p style={{ color: "#666", fontSize: "0.9rem", marginBottom: "2.5rem" }}>
        Last updated: May 02, 2026
      </p>

      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You. We use Your Personal Data to provide and improve the Service. By
        using the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words whose initial letters are capitalized have meanings defined
        under the following conditions. The following definitions shall have the
        same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by, or is under common control with a party, where
          &quot;control&quot; means ownership of 50% or more of the shares,
          equity interest or other securities entitled to vote for election of
          directors or other managing authority.
        </li>
        <li>
          <strong>Application</strong> refers to Zera Africa, the software
          program provided by the Company.
        </li>
        <li>
          <strong>Company</strong> (referred to as either &quot;the
          Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
          this Privacy Policy) refers to Ed Partners Africa Limited, 4th Floor
          Parkfield Place Along Waiyaki Way.
        </li>
        <li>
          <strong>Country</strong> refers to Kenya.
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cell phone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> (or &quot;Personal Information&quot;)
          is any information that relates to an identified or identifiable
          individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Application.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself.
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company on behalf of which such individual is
          accessing or using the Service.
        </li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul>
        <li>First name and last name</li>
        <li>Phone number</li>
      </ul>

      <h4>Usage Data</h4>
      <p>
        Usage Data is collected automatically when using the Service. Usage Data
        may include information such as Your Device&apos;s Internet Protocol
        address (e.g. IP address), browser type, browser version, the pages of
        our Service that You visit, the time and date of Your visit, the time
        spent on those pages, unique device identifiers and other diagnostic
        data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device&apos;s unique
        ID, the IP address of Your mobile device, Your mobile operating system,
        the type of mobile Internet browser You use, unique device identifiers
        and other diagnostic data.
      </p>

      <h4>Information Collected while Using the Application</h4>
      <p>
        While using Our Application, in order to provide features of Our
        Application, We may collect, with Your prior permission:
      </p>
      <ul>
        <li>Information regarding your location</li>
        <li>
          Pictures and other information from your Device&apos;s camera and
          photo library
        </li>
      </ul>
      <p>
        You can enable or disable access to this information at any time,
        through Your Device settings.
      </p>

      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>
          <strong>To provide and maintain our Service</strong>, including to
          monitor the usage of our Service.
        </li>
        <li>
          <strong>To manage Your Account:</strong> to manage Your registration
          as a user of the Service.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> the development,
          compliance and undertaking of contracts with Us through the Service.
        </li>
        <li>
          <strong>To contact You:</strong> by email, telephone calls, SMS, or
          other equivalent forms of electronic communication regarding updates
          or informative communications related to the Service.
        </li>
        <li>
          <strong>To provide You</strong> with news, special offers, and general
          information about other goods, services and events which We offer.
        </li>
        <li>
          <strong>To manage Your requests:</strong> to attend and manage Your
          requests to Us.
        </li>
        <li>
          <strong>For business transfers:</strong> to evaluate or conduct a
          merger, divestiture, restructuring, reorganization, dissolution, or
          other sale or transfer of some or all of Our assets.
        </li>
        <li>
          <strong>For other purposes:</strong> such as data analysis,
          identifying usage trends, and improving our Service.
        </li>
      </ul>

      <p>We may share Your Personal Data in the following situations:</p>
      <ul>
        <li>
          <strong>With Service Providers:</strong> to monitor and analyze the
          use of our Service.
        </li>
        <li>
          <strong>For business transfers:</strong> in connection with any
          merger, sale of Company assets, financing, or acquisition.
        </li>
        <li>
          <strong>With Affiliates:</strong> who are required to honor this
          Privacy Policy.
        </li>
        <li>
          <strong>With business partners:</strong> to offer You certain
          products, services or promotions.
        </li>
        <li>
          <strong>With Your consent:</strong> for any other purpose with Your
          consent.
        </li>
      </ul>

      <h2>Retention of Your Personal Data</h2>
      <p>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. Retention
        periods include:
      </p>
      <ul>
        <li>
          <strong>User Accounts:</strong> retained for the duration of your
          account relationship plus up to 24 months after account closure.
        </li>
        <li>
          <strong>Application usage statistics:</strong> up to 24 months.
        </li>
        <li>
          <strong>Server logs (IP addresses, access times):</strong> up to 24
          months for security monitoring and troubleshooting.
        </li>
      </ul>
      <p>
        We may retain Personal Data beyond the periods stated above for legal
        obligations, legal claims, explicit user requests, or technical backup
        limitations. When retention periods expire, We securely delete or
        anonymize Personal Data.
      </p>

      <h2>Transfer of Your Personal Data</h2>
      <p>
        Your information, including Personal Data, may be transferred to and
        maintained on computers located outside of Your state, province,
        country, or other governmental jurisdiction where data protection laws
        may differ. The Company will take all steps reasonably necessary to
        ensure that Your data is treated securely and in accordance with this
        Privacy Policy.
      </p>

      <h2>Delete Your Personal Data</h2>
      <p>
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You. You may update, amend,
        or delete Your information at any time by signing in to Your Account and
        visiting the account settings section, or by contacting Us directly.
      </p>
      <p>
        Please note that We may need to retain certain information when we have
        a legal obligation or lawful basis to do so.
      </p>

      <h2>Disclosure of Your Personal Data</h2>
      <h3>Business Transactions</h3>
      <p>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data becomes subject to a different Privacy Policy.
      </p>

      <h3>Law Enforcement</h3>
      <p>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </p>

      <h3>Other Legal Requirements</h3>
      <p>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          Protect the personal safety of Users of the Service or the public
        </li>
        <li>Protect against legal liability</li>
      </ul>

      <h2>Security of Your Personal Data</h2>
      <p>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially reasonable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>

      <h2>Children&apos;s Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 16. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 16. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. We
        will take steps to remove that information from Our servers.
      </p>

      <h2>Links to Other Websites</h2>
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. We strongly advise You to review the Privacy Policy of every site
        You visit. We have no control over and assume no responsibility for the
        content, privacy policies or practices of any third party sites or
        services.
      </p>

      <h2>Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page and
        updating the &quot;Last updated&quot; date at the top of this Privacy
        Policy. You are advised to review this Privacy Policy periodically for
        any changes.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul>
        <li>
          By email:{" "}
          <a href="mailto:customercare@edpartnersafrica.com">
            customercare@edpartnersafrica.com
          </a>
        </li>
      </ul>

      <style>{`
        h2 { font-size: 1.3rem; margin-top: 2.5rem; margin-bottom: 0.5rem; }
        h3 { font-size: 1.1rem; margin-top: 1.5rem; margin-bottom: 0.4rem; }
        h4 { font-size: 1rem; margin-top: 1.2rem; margin-bottom: 0.3rem; }
        p  { margin-bottom: 0.9rem; }
        ul { padding-left: 1.5rem; margin-bottom: 0.9rem; }
        li { margin-bottom: 0.4rem; }
        a  { color: #111; }
      `}</style>
    </div>
  );
}
